"""Prepare Candidate E (the closed-loop economic agent) for submission.

Every other packager in this directory wraps a recorded route: it verifies
a model blob, checks its hash, and stacks the guard agents around it.
Candidate E has no blob. It is a policy that reads the observation and
prices its own decisions, so packaging it is only a matter of inlining the
modules it imports, in dependency order, into one file Kaggle can run.

The dependency graph is small and acyclic:

    core/routing      -- no local imports
    rl/demand         -- no local imports
    rl/market         -- no local imports
    rl/economics      -- candidates.market
    rl/demand_sales   -- candidates.demand
    rl/candidate_e    -- all of the above, plus `AgentAction` from
                         rl.runtime

`rl/runtime` is deliberately *not* inlined. Candidate E takes exactly one
name from it, the alias `AgentAction = dict[str, Any]`, while the module
itself imports the whole calendar agent and residual-policy stack. Pulling
that in would drag several hundred unrelated lines into the submission for
the sake of a type alias, so the alias is re-declared instead and the
import is stripped like every other local one.

Equivalence is checked rather than assumed: `tools/validation/
validate_candidate_e_equivalence.py` runs the packaged module and
`candidates.candidate_e` over identical games and requires the actions to match
turn for turn.
"""

from __future__ import annotations

import ast
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DEPENDENCIES = (
    ROOT / "core" / "routing.py",
    ROOT / "candidates" / "demand.py",
    ROOT / "candidates" / "market.py",
    ROOT / "candidates" / "economics.py",
    ROOT / "candidates" / "demand_sales.py",
)
CANDIDATE_E_PATH = ROOT / "candidates" / "candidate_e.py"
SOURCE_PATHS = DEPENDENCIES + (CANDIDATE_E_PATH,)
OUTPUT = ROOT / "submissions" / "candidate-e" / "main.py"
MANIFEST = ROOT / "submissions" / "candidate-e" / "manifest.json"
STRIPPED_IMPORT_PREFIXES = ("agents.", "policies.", "core.", "rl.", "stack.", "candidates.")

PREAMBLE = '''"""Candidate E -- generated by tools/packaging/\
prepare_candidate_e_submission.py. Do not edit by hand."""
from __future__ import annotations
import math
from typing import Any, Callable, Iterable, Sequence

AgentAction = dict[str, Any]
Baseline = Callable[[dict[str, Any]], AgentAction]
'''


def _strip_imports(module: ast.Module) -> list[ast.stmt]:
    """Drop `__future__` and local-package imports; keep stdlib ones."""
    return [
        node
        for node in module.body
        if not (
            isinstance(node, ast.ImportFrom)
            and (
                node.module == "__future__"
                or (
                    node.module is not None
                    and node.module.startswith(STRIPPED_IMPORT_PREFIXES)
                )
            )
        )
    ]


def _source_body(path: Path) -> list[ast.stmt]:
    return _strip_imports(ast.parse(path.read_text(encoding="utf-8")))


def build_source() -> str:
    module = ast.parse(PREAMBLE)
    for path in SOURCE_PATHS:
        module.body.extend(_source_body(path))
    source = ast.unparse(ast.fix_missing_locations(module)) + "\n"
    tree = ast.parse(source)
    exported = {
        node.name
        for node in tree.body
        if isinstance(node, ast.FunctionDef)
    }
    if "agent" not in exported:
        raise ValueError("packaged Candidate E exports no `agent`")
    return source


def combined_source_hash() -> str:
    digest = hashlib.sha256()
    for path in SOURCE_PATHS:
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def main() -> None:
    source = build_source()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(source, encoding="utf-8")
    manifest: dict[str, Any] = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "competition": "kaggriculture",
        "agent": "main.py",
        "sha256": hashlib.sha256(OUTPUT.read_bytes()).hexdigest(),
        "combined_source_sha256": combined_source_hash(),
        "kind": "closed_loop_policy",
        "note": (
            "Candidate E carries no recorded route. It reads the "
            "observation and prices each decision, so the package is the "
            "inlined source of candidates/candidate_e.py and its five local "
            "dependencies."
        ),
        "source_files": [
            str(path.relative_to(ROOT)).replace("\\", "/")
            for path in SOURCE_PATHS
        ],
    }
    MANIFEST.write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(f"wrote {OUTPUT.relative_to(ROOT)} "
          f"({OUTPUT.stat().st_size:,} bytes)")
    print(f"wrote {MANIFEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
