"""Prepare Candidate G for Kaggle.

G lives in `candidates/candidate_g.py` and imports from four local modules. Kaggle
wants one self-contained `main.py`, so this parses each dependency, strips
the local imports, and concatenates them in dependency order ahead of the
agent.

`rl.runtime` is not inlined: G takes only the `AgentAction` type alias
from it, and that module pulls the whole calendar-agent, policy and
feature stack behind it. The alias is re-declared locally instead.

Run `tools/eval/preflight_candidate_g.py` after this to check the built
file imports with the repo off the path, plays both seats to completion,
and matches the source decision for decision.

    python -m tools.packaging.prepare_candidate_g_submission
"""

from __future__ import annotations

import ast
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

ROUTING_PATH = ROOT / "core" / "routing.py"
MARKET_PATH = ROOT / "candidates" / "market.py"
DEMAND_PATH = ROOT / "candidates" / "demand.py"
ECONOMICS_PATH = ROOT / "candidates" / "economics.py"
AGENT_PATH = ROOT / "candidates" / "candidate_g.py"

# Order matters: economics reads marginal_price out of market.
SOURCE_PATHS = (
    ROUTING_PATH,
    MARKET_PATH,
    DEMAND_PATH,
    ECONOMICS_PATH,
    AGENT_PATH,
)

OUTPUT = ROOT / "submissions" / "candidate-g" / "main.py"
MANIFEST = ROOT / "submissions" / "candidate-g" / "manifest.json"

LOCAL_PREFIXES = ("core.", "rl.", "agents.", "policies.", "stack.", "candidates.")

PREAMBLE = '''"""Candidate G, packaged for Kaggle.

Generated by tools/packaging/prepare_candidate_g_submission.py -- edit the
sources under rl/ and core/, never this file.
"""

from __future__ import annotations

import math
from collections import Counter
from collections.abc import Iterable
from typing import Any, Dict, List

# rl.runtime supplies only this alias, and importing it would drag in the
# whole calendar-agent stack.
AgentAction = Dict[str, Any]
'''


def _body(path: Path) -> list[ast.stmt]:
    """Every statement in a module except imports of our own code."""
    module = ast.parse(path.read_text(encoding="utf-8"))
    kept: list[ast.stmt] = []
    for node in module.body:
        if isinstance(node, ast.ImportFrom):
            if node.module == "__future__":
                continue
            if node.module and node.module.startswith(LOCAL_PREFIXES):
                continue
            if node.module in ("typing", "collections", "collections.abc"):
                continue
        if isinstance(node, ast.Import):
            if any(a.name.startswith(LOCAL_PREFIXES) for a in node.names):
                continue
            if all(a.name == "math" for a in node.names):
                continue
        kept.append(node)
    return kept


def build_source() -> str:
    merged = ast.parse(PREAMBLE)
    for path in SOURCE_PATHS:
        merged.body.extend(_body(path))
    return ast.unparse(ast.fix_missing_locations(merged)) + "\n"


def source_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> None:
    source = build_source()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(source, encoding="utf-8")

    manifest = {
        "candidate": "candidate-g",
        "entry": "main.py",
        "built_at": datetime.now(timezone.utc).isoformat(),
        "sha256": source_hash(source),
        "bytes": len(source.encode("utf-8")),
        "sources": [
            {
                "path": str(p.relative_to(ROOT)).replace("\\", "/"),
                "sha256": hashlib.sha256(p.read_bytes()).hexdigest(),
            }
            for p in SOURCE_PATHS
        ],
    }
    MANIFEST.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"wrote {OUTPUT.relative_to(ROOT)} "
          f"({manifest['bytes']:,} bytes, sha {manifest['sha256'][:12]})")


if __name__ == "__main__":
    main()
