"""Prepare Candidate H-D (demand-timed, denial-sensitive) for Kaggle.

The agent lives in `candidates/candidateHdeepseek.py` and imports from four local
modules. Kaggle wants one self-contained `main.py`, so this parses each
dependency, strips the local imports, and concatenates them in dependency
order ahead of the agent itself.

`rl.runtime` is deliberately not inlined. The agent takes only the
`AgentAction` type alias from it, and that module pulls in the whole
calendar-agent, policy and feature stack behind it; the alias is
re-declared locally instead.

    python -m tools.packaging.prepare_candidate_hd_submission
"""

from __future__ import annotations

import ast
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

ROUTING_PATH = ROOT / "core" / "routing.py"
MARKET_PATH = ROOT / "candidates" / "market.py"
DEMAND_PATH = ROOT / "candidates" / "demand.py"
ECONOMICS_PATH = ROOT / "candidates" / "economics.py"
AGENT_PATH = ROOT / "candidates" / "candidateHdeepseek.py"

# Dependency order matters: economics reads marginal_price out of market.
SOURCE_PATHS = (
    ROUTING_PATH,
    MARKET_PATH,
    DEMAND_PATH,
    ECONOMICS_PATH,
    AGENT_PATH,
)

OUTPUT = ROOT / "submissions" / "candidate-hd" / "main.py"
MANIFEST = ROOT / "submissions" / "candidate-hd" / "manifest.json"

LOCAL_PREFIXES = ("core.", "rl.", "agents.", "policies.", "stack.", "candidates.")

PREAMBLE = '''"""Candidate H-D, packaged for Kaggle.

Generated by tools/packaging/prepare_candidate_hd_submission.py -- edit the
sources under rl/ and core/, never this file.
"""

from __future__ import annotations

import math
from collections import Counter
from collections.abc import Iterable
from typing import Any, Dict, List

# rl.runtime only supplies this alias, and importing it would drag in the
# whole calendar-agent stack.
AgentAction = Dict[str, Any]
'''


def _body(path: Path) -> list[ast.stmt]:
    """Every statement in a module except its imports of our own code."""
    module = ast.parse(path.read_text(encoding="utf-8"))
    kept: list[ast.stmt] = []
    for node in module.body:
        if isinstance(node, ast.ImportFrom):
            if node.module == "__future__":
                continue
            if node.module and node.module.startswith(LOCAL_PREFIXES):
                continue
            if node.module in ("typing", "collections", "collections.abc"):
                continue
        if isinstance(node, ast.Import):
            if any(a.name.startswith(LOCAL_PREFIXES) for a in node.names):
                continue
            if all(a.name in ("math",) for a in node.names):
                continue
        kept.append(node)
    return kept


def build_source() -> str:
    merged = ast.parse(PREAMBLE)
    for path in SOURCE_PATHS:
        merged.body.extend(_body(path))
    return ast.unparse(ast.fix_missing_locations(merged)) + "\n"


def source_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> None:
    source = build_source()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(source, encoding="utf-8")

    manifest = {
        "candidate": "candidate-hd",
        "entry": "main.py",
        "built_at": datetime.now(timezone.utc).isoformat(),
        "sha256": source_hash(source),
        "bytes": len(source.encode("utf-8")),
        "sources": [
            {
                "path": str(p.relative_to(ROOT)).replace("\\", "/"),
                "sha256": hashlib.sha256(p.read_bytes()).hexdigest(),
            }
            for p in SOURCE_PATHS
        ],
    }
    MANIFEST.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"wrote {OUTPUT.relative_to(ROOT)} "
          f"({manifest['bytes']:,} bytes, sha {manifest['sha256'][:12]})")


if __name__ == "__main__":
    main()
