"""Package Candidate J into a single standalone ``main.py``.

J is written as a normal module and imports five others -- ``core.routing``,
``candidates.demand``, ``candidates.economics``, ``candidates.market`` and ``rl.runtime``. A Kaggle
submission is one file with nothing beside it, so those imports have to be
inlined, in dependency order, with J's own body last.

Two properties are non-negotiable and both are checked here rather than
assumed:

**``agent`` must be the last callable defined in the file.**
``kaggle_environments`` loads a submission with ``get_last_callable``, which
takes the final callable in the module rather than the one named ``agent``.
A helper that lands after it becomes the agent, every action is rejected as
malformed, and the farm stands still for thirty days while the file looks
perfectly correct. That is not hypothetical: it is how Candidate I's first
submission came back 3000/3000, and it was invisible because the *source
module* had been measured and the *packaged file* had not.

**The packaged file must make the same decisions as the source.** A full
game is played with the source agent, every observation it sees is recorded,
and the packaged file is fed the same sequence and compared action by
action. J carries state between turns (``_EN_ROUTE``, ``_FAILED``), so
replaying the sequence exercises that too.

Then the file is played the way Kaggle plays it -- by path, through
``get_last_callable`` -- and must finish a real game with a real score.

    python -m tools.packaging.prepare_candidate_j_submission
"""

from __future__ import annotations

import argparse
import copy
import importlib.util
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "submissions" / "candidate-j" / "main.py"

# In dependency order: each may use only the ones above it.
#
# rl/runtime.py is deliberately NOT here. It is a bridge to an abandoned
# reinforcement-learning "residual policy" experiment, and its only import
# candidate_j.py actually uses is the AgentAction type alias -- but the
# file ALSO does `from agents.experimental_distilled_calendar_agent import
# decide as calendar`, a LOCAL PROJECT IMPORT that exists in this repo and
# nowhere else. Inlining the whole file carried that import into every
# submission built from these PARTS, and it always resolved fine locally
# because every test script here starts with `sys.path.insert(0, ROOT)` --
# the repo is never actually absent in development, the one condition
# that matters on Kaggle's bare server. `agent()` is never even reached:
# `get_last_callable` executes the WHOLE module top to bottom first, and
# that import raises before any of our own code runs. Both J's and K's
# first submissions failed on exactly this. AgentAction is defined
# directly below instead, which is the only thing ever actually needed.
PARTS = (
    ROOT / "candidates" / "economics.py",
    ROOT / "candidates" / "market.py",
    ROOT / "candidates" / "demand.py",
    ROOT / "core" / "routing.py",
    ROOT / "candidates" / "candidate_j.py",
)
# Imports of our own modules are dropped; the definitions arrive inline.
LOCAL_IMPORT = re.compile(
    r"^\s*(?:from\s+(?:rl|core)[\w.]*\s+import\s.*|import\s+(?:rl|core)[\w.]*.*)$")
FUTURE = re.compile(r"^\s*from\s+__future__\s+import\s.*$")
DOCSTRING = re.compile(r'^\s*(?:"""|\'\'\')')


def strip_module(path: Path) -> str:
    """One module's body: no local imports, no __future__, no module docstring.

    The docstrings are the project's record of why each constant holds the
    value it does, and they are worth keeping, so only the *module-level*
    docstring of each part is dropped -- every function keeps its own.
    """
    lines = path.read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    index = 0
    # Skip a leading module docstring.
    while index < len(lines) and not lines[index].strip():
        index += 1
    if index < len(lines) and DOCSTRING.match(lines[index]):
        quote = lines[index].strip()[:3]
        if lines[index].strip().count(quote) >= 2 and len(
                lines[index].strip()) > 3:
            index += 1
        else:
            index += 1
            while index < len(lines) and quote not in lines[index]:
                index += 1
            index += 1
    for line in lines[index:]:
        if LOCAL_IMPORT.match(line) or FUTURE.match(line):
            continue
        out.append(line)
    return "\n".join(out).strip("\n")


def build() -> str:
    header = [
        '"""Candidate J -- one file, assembled by',
        '   tools/packaging/prepare_candidate_j_submission.py',
        "",
        "   Do not edit this file. Edit candidates/candidate_j.py and repackage.",
        "   `agent` must remain the last callable defined here: Kaggle loads a",
        "   submission with get_last_callable, which takes the final callable",
        "   in the module and not the one named agent.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "import math",
        "import os",
        "import random",
        "import sys",
        "from typing import Any",
        "",
        "# The only thing candidate_j.py ever used from rl/runtime.py; see",
        "# PARTS above for why the rest of that file is not inlined.",
        "AgentAction = dict[str, Any]",
        "",
    ]
    body = [header[0:]]
    chunks = ["\n".join(header)]
    for part in PARTS:
        chunks.append(f"\n# --- {part.relative_to(ROOT).as_posix()} "
                      + "-" * max(0, 60 - len(part.name)) + "\n")
        chunks.append(strip_module(part))
    del body
    return "\n".join(chunks) + "\n"


def load_packaged(path: Path):
    spec = importlib.util.spec_from_file_location("candidate_j_packaged", path)
    module = importlib.util.module_from_spec(spec)
    saved = list(sys.path)
    # Import with the repository OFF sys.path, so a missed inline shows up
    # here as an ImportError instead of on the ladder as a dead farm.
    sys.path[:] = [p for p in sys.path
                   if Path(p or ".").resolve() != ROOT.resolve()]
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path[:] = saved
    return module


def last_callable_name(path: Path) -> str:
    """What `get_last_callable` will actually pick out of this file."""
    import ast

    tree = ast.parse(path.read_text(encoding="utf-8"))
    names = [node.name for node in tree.body
             if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))]
    if not names:
        raise SystemExit("packaged file defines no functions at all")
    return names[-1]


def check_only_stdlib_imports(path: Path) -> None:
    """Refuse to ship a file that imports anything outside the standard
    library.

    This is the check that would have caught the bug that actually shipped:
    `rl/runtime.py`, inlined whole, carried `from
    agents.experimental_distilled_calendar_agent import decide` into every
    packaged submission built from it. It always resolved in development,
    because every test script here starts with `sys.path.insert(0, ROOT)`
    -- the repo is never actually absent locally, which is the one
    condition that is guaranteed true on Kaggle's bare server. Neither
    `get_last_callable`'s own load nor a full local game caught it, because
    both ran with the repo still on `sys.path`. A submission has no file
    beside it and no project to fall back on, so nothing outside
    `sys.stdlib_module_names` may appear in a top-level import anywhere in
    the file.
    """
    import ast

    tree = ast.parse(path.read_text(encoding="utf-8"))
    bad: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                top = alias.name.split(".")[0]
                if top not in sys.stdlib_module_names:
                    bad.append(f"import {alias.name}")
        elif isinstance(node, ast.ImportFrom):
            if node.module is None or node.level > 0:
                continue  # relative import; cannot exist at module level here
            top = node.module.split(".")[0]
            if top not in sys.stdlib_module_names:
                bad.append(f"from {node.module} import ...")
    if bad:
        raise SystemExit(
            "packaged file imports something outside the standard "
            "library -- it will not exist on Kaggle's server even though "
            "it resolves here, the same way rl/runtime.py's import once "
            "did:\n  " + "\n  ".join(sorted(set(bad))))


def verify(path: Path) -> dict:
    from kaggle_environments import make
    from kaggle_environments.agent import get_last_callable

    check_only_stdlib_imports(path)
    name = last_callable_name(path)
    if name != "agent":
        raise SystemExit(
            f"the last callable in the packaged file is {name!r}, not 'agent'. "
            "Kaggle would run that instead and the farm would stand still.")

    sys.path.insert(0, str(ROOT))
    import candidates.candidate_j as source  # noqa: E402

    seen: list[tuple[dict, Any]] = []

    def recorder(observation, configuration=None):
        action = source.agent(observation, configuration)
        seen.append((copy.deepcopy(dict(observation)),
                     copy.deepcopy(action)))
        return action

    env = make("kaggriculture",
               configuration={"episodeSteps": 720, "seed": 4242,
                              "runTimeout": 36000, "actTimeout": 60},
               debug=False)
    env.run([recorder, "random"])
    source_score = float(env.steps[-1][0].get("reward") or 0.0)

    packaged = load_packaged(path)
    if not callable(getattr(packaged, "agent", None)):
        raise SystemExit("packaged main.py does not expose agent()")
    packaged._EN_ROUTE.clear()
    mismatches = []
    for observation, expected in seen:
        got = packaged.agent(observation, None)
        if got != expected:
            mismatches.append({"step": observation.get("step"),
                               "expected": expected, "got": got})
            if len(mismatches) >= 3:
                break
    if mismatches:
        raise SystemExit("packaged agent diverges from the source:\n"
                         + json.dumps(mismatches, indent=1)[:2000])
    if getattr(packaged, "_FAILED", False):
        raise SystemExit("the packaged agent raised during the replay; its "
                         "traceback is above and every turn after it passed")

    # The check whose absence put a dead agent on the ladder: play the FILE,
    # loaded the way Kaggle loads it, in a real game.
    played = get_last_callable(path.read_text(encoding="utf-8"))
    env2 = make("kaggriculture",
                configuration={"episodeSteps": 720, "seed": 909,
                               "runTimeout": 36000, "actTimeout": 60},
                debug=False)
    env2.run([played, "random"])
    final = env2.steps[-1]
    score = float(final[0].get("reward") or 0.0)
    status = str(final[0].get("status"))
    if status != "DONE":
        raise SystemExit(f"packaged file did not finish cleanly: {status}")
    if score < 30_000:
        raise SystemExit(f"packaged file scored {score:,.0f} against random, "
                         "which is far too low to be the real agent")
    return {"last_callable": name, "source_score": source_score,
            "packaged_score": score, "steps_compared": len(seen),
            "bytes": path.stat().st_size}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build(), encoding="utf-8")
    print(f"wrote {args.out.relative_to(ROOT).as_posix()}")
    report = verify(args.out)
    print("\nverified:")
    for key, value in report.items():
        if isinstance(value, float):
            print(f"  {key:16s} {value:,.0f}")
        else:
            print(f"  {key:16s} {value}")
    print("\n  agent() is the last callable, the packaged file makes the same")
    print("  decisions as the source over a whole game, and it plays a clean")
    print("  game when loaded by path the way Kaggle loads it.")


if __name__ == "__main__":
    main()
