"""Candidate H-D, packaged for Kaggle.

Generated by tools/packaging/prepare_candidate_hd_submission.py -- edit the
sources under rl/ and core/, never this file.
"""
from __future__ import annotations
import math
from collections import Counter
from collections.abc import Iterable
from typing import Any, Dict, List
AgentAction = Dict[str, Any]
'Deterministic shortest-path primitives for the obstacle-free farm grid.'
Position = tuple[int, int]
Action = list[str]

def distance(origin: Position, target: Position) -> int:
    """Return the exact shortest path length on the farm grid."""
    return abs(origin[0] - target[0]) + abs(origin[1] - target[1])

def step_toward(origin: Position, target: Position, action_at_target: Action) -> Action:
    """Take one deterministic shortest-path step or act at the target."""
    if origin == target:
        return action_at_target
    if target[0] < origin[0]:
        return ['WEST']
    if target[0] > origin[0]:
        return ['EAST']
    if target[1] < origin[1]:
        return ['NORTH']
    return ['SOUTH']

def nearest_position(origin: Position, targets: Iterable[Position]) -> Position:
    """Return the nearest target with stable row-major tie-breaking."""
    return min(targets, key=lambda target: (distance(origin, target), target[1], target[0]))

def pair_route_cost(positions: tuple[Position, Position], target: Position) -> tuple[int, int]:
    """Rank a paired route by completion time, then total travel."""
    distances = tuple((distance(position, target) for position in positions))
    return (max(distances), sum(distances))
"What a unit will actually fetch, given everything already sold.\n\nAgent E used to price every decision at the market's spot quote. That is\nwrong in a way that costs whole strategies, because this market is a\ndepleting resource shared by both players: the price of an item is a\nfunction of the market's inventory, and every unit sold pushes that\ninventory up and the price down. Selling one melon at 250 says nothing\nabout selling two hundred, which is what the curve below shows -- melon\npays 26,727 coins for the first 400 units, but the last 200 of them are\nworth one coin each.\n\nThe curve is transcribed from `market_price` in the simulator, not\nguessed. `price(inventory) = base -/+ amp * f(|inventory - I0|)` with\n`amp = target * base / f(T)`, floored at 1.\n\nWhat it reveals, and what Agent E is built on:\n\n| item       | 400 units fetch | price at unit 400 |\n| ---------- | --------------- | ----------------- |\n| FERTILIZER |          24,040 |                20 |\n| EGG        |          16,559 |            **40** |\n| MELON      |          26,727 |                 1 |\n| WHEAT      |           8,313 |                20 |\n| WOOL       |           8,269 |                 1 |\n| MILK       |           6,505 |                 1 |\n| STRAWBERRY |           4,147 |                 1 |\n\nMilk, wool and strawberry are exhausted inside 50 to 90 units. **Egg is\nthe only product in the game that never collapses** -- its curve is\nlogarithmic with the largest T of any product -- and in real games against\nelite opponents it finishes 150 to 300 units *below* equilibrium at 59 to\n68 coins, above its own base of 50, because nobody keeps geese. That is\nthe opening Agent E is built to take.\n"
MARKET_PARAMS: dict[str, dict[str, Any]] = {'WHEAT': dict(base=25, T=400, below='sqrt', below_t=0.8, above='log', above_t=0.2), 'CARROT': dict(base=35, T=450, below='hinge', below_t=1.0, above='sqrt', above_t=0.7), 'TOMATO': dict(base=60, T=200, below='hinge', below_t=0.4, above='sqrt', above_t=0.6), 'STRAWBERRY': dict(base=120, T=100, below='sqrt', below_t=0.7, above='linear', above_t=1.6), 'MELON': dict(base=250, T=300, below='log', below_t=0.2, above='sq', above_t=3.6), 'EGG': dict(base=50, T=332, below='hinge', below_t=0.4, above='log', above_t=0.2), 'MILK': dict(base=160, T=122, below='sqrt', below_t=0.6, above='linear', above_t=1.6), 'WOOL': dict(base=200, T=105, below='log', below_t=0.2, above='sq', above_t=3.2), 'FERTILIZER': dict(base=100, T=200, below='linear', below_t=0.4, above='linear', above_t=0.4)}
MARKET_I0 = 10000
PRICE_FLOOR = 1
HINGE_GAIN = 8.0

def _shape(func: str, x: float, T: float) -> float:
    x = max(0.0, x)
    if func == 'linear':
        return x
    if func == 'sq':
        return x * x
    if func == 'sqrt':
        return math.sqrt(x)
    if func == 'log':
        return math.log(1.0 + x)
    if func == 'hinge':
        if not T or T <= 0:
            return x
        u = x / T
        return u + HINGE_GAIN * max(0.0, u - 1.0) ** 2
    return x

def price_at(item: str, inventory: float) -> float:
    """The simulator's quote for `item` at that market inventory."""
    p = MARKET_PARAMS.get(item)
    if p is None:
        return 0.0
    base, T = (float(p['base']), float(p['T']))
    if inventory <= MARKET_I0:
        amp = p['below_t'] * base / _shape(p['below'], T, T)
        value = base + amp * _shape(p['below'], MARKET_I0 - inventory, T)
    else:
        amp = p['above_t'] * base / _shape(p['above'], T, T)
        value = base - amp * _shape(p['above'], inventory - MARKET_I0, T)
    return float(max(PRICE_FLOOR, round(value)))

def inventory_of(observation: dict[str, Any], item: str) -> float:
    """Market inventory of `item`, falling back to equilibrium."""
    market = observation.get('market') or {}
    stock = market.get('inventory') or {}
    value = stock.get(item)
    if isinstance(value, (int, float)):
        return float(value)
    return float(MARKET_I0)

def sale_revenue(observation: dict[str, Any], item: str, units: float, sold_already: float=0.0) -> float:
    """Coins from selling `units`, walking the price down as it goes.

    The simulator re-quotes after every single unit, so a batch is the sum
    of the curve over the units, not the spot price times the count.

    `sold_already` shifts the starting point, which is how production is
    valued at the margin: the tenth cow's milk is worth what is left after
    the first nine have flooded the market, and a negative value accounts
    for what the town will still consume before we get there.
    """
    units = int(max(0.0, units))
    if units <= 0:
        return 0.0
    start = inventory_of(observation, item) + sold_already
    return float(sum((price_at(item, start + n) for n in range(units))))

def marginal_price(observation: dict[str, Any], item: str, already: float=0.0) -> float:
    """What the next unit fetches once `already` more have been sold.

    This is the number every production decision should use. Pricing a
    thirteenth melon at the spot quote of the first is what makes an agent
    plant a field of them and sell them for one coin apiece.
    """
    return price_at(item, inventory_of(observation, item) + max(0.0, already))

def headroom(observation: dict[str, Any], item: str, floor: float) -> int:
    """How many units can still be sold before the price drops below `floor`.

    Used to cap production: there is no point growing a fourteenth melon
    tile when the market will only absorb sixty more melons above a price
    worth the tile.
    """
    inventory = inventory_of(observation, item)
    if price_at(item, inventory) < floor:
        return 0
    low, high = (0, 2000)
    while low < high:
        mid = (low + high + 1) // 2
        if price_at(item, inventory + mid) >= floor:
            low = mid
        else:
            high = mid - 1
    return low
'Read the town\'s demand for each product from the live observation.\n\nThe simulator\'s demand engine (`_town_consume` in kaggriculture.py) is\nfully deterministic and fully observable:\n\n* every `townShopSellInterval` (4) steps, each unlocked shop instance\n  removes one unit of each product it sells -- **two** if the shop sells\n  only a single product, which is YARN_STORE (wool) and PET_CAFE (carrot);\n* every `townCenterSellInterval` (24) steps the town centre removes one\n  unit of every product except FERTILIZER;\n* shops unlock roughly every three days, drawn **at random with\n  replacement** from the eight types and capped at eight instances.\n\nBecause the draw is random per episode, every game has a different demand\nprofile, and because `observation["town"]["unlocked_shops"]` lists the\ninstances, that profile can be computed exactly rather than guessed.\n\nWhy this matters (rl/GOAL.md section 9u and 9v): the resulting price\nswings are enormous -- wool ends a game worth 1 coin or 239 depending on\nwhether YARN_STORE was drawn, milk 5 or 110 -- and adaptation to it is\nthe single cleanest correlate of leaderboard rank we have measured:\nwool-demand-to-sheep-bought runs +0.672 for teams at 2850+, +0.323 for\n2400-2849 and **+0.000 below 2400**. A frozen tape scores structurally\nzero there, which is where every candidate this project has shipped sits.\n'
SHOPS: dict[str, tuple[str, ...]] = {'BAKERY': ('EGG', 'WHEAT'), 'PIZZA_SHOP': ('MILK', 'TOMATO', 'WHEAT'), 'BRUNCH_SPOT': ('EGG', 'WHEAT', 'STRAWBERRY'), 'YARN_STORE': ('WOOL',), 'ICE_CREAM_SHOP': ('STRAWBERRY', 'MILK', 'WHEAT'), 'PET_CAFE': ('CARROT',), 'SMOOTHIE_SHOP': ('STRAWBERRY', 'MILK'), 'FARMERS_MARKET': ('WHEAT', 'CARROT', 'TOMATO', 'STRAWBERRY')}
PRODUCTS: tuple[str, ...] = ('WHEAT', 'CARROT', 'TOMATO', 'STRAWBERRY', 'MELON', 'EGG', 'MILK', 'WOOL', 'FERTILIZER')
TOWN_CENTRE: tuple[str, ...] = tuple((p for p in PRODUCTS if p != 'FERTILIZER'))
SHOP_INTERVAL = 4
CENTRE_INTERVAL = 24
EPISODE_STEPS = 720
ANIMAL_PRODUCT = {'COW': 'MILK', 'SHEEP': 'WOOL', 'GOOSE': 'EGG'}

def unlocked_shops(observation: dict[str, Any]) -> list[str]:
    town = observation.get('town') or {}
    shops = town.get('unlocked_shops') or []
    return [str(s) for s in shops if str(s) in SHOPS]

def shop_demand_per_event(shops: list[str]) -> dict[str, int]:
    """Units each product loses every `SHOP_INTERVAL` steps."""
    demand = {p: 0 for p in PRODUCTS}
    for shop in shops:
        products = SHOPS.get(shop)
        if not products:
            continue
        multiplier = 2 if len(products) == 1 else 1
        for product in products:
            demand[product] += multiplier
    return demand

def demand_rate(observation: dict[str, Any]) -> dict[str, float]:
    """Units per step the town will absorb, at the current shop set."""
    per_event = shop_demand_per_event(unlocked_shops(observation))
    rate = {p: per_event[p] / SHOP_INTERVAL for p in PRODUCTS}
    for product in TOWN_CENTRE:
        rate[product] += 1.0 / CENTRE_INTERVAL
    return rate

def remaining_demand(observation: dict[str, Any]) -> dict[str, float]:
    """Units the town will still absorb between now and the final step.

    Held at the *current* shop set, so this understates late demand while
    shops are still unlocking. That bias is deliberate: it never promises
    demand that has not been observed yet.
    """
    step = int(observation.get('step', 0))
    left = max(0, EPISODE_STEPS - step)
    return {p: r * left for p, r in demand_rate(observation).items()}

def preferred_animal(observation: dict[str, Any], candidates: tuple[str, ...]=('COW', 'SHEEP'), *, margin: float=1.25) -> str | None:
    """Which pasture animal this town actually wants, if either clearly is.

    Compares expected remaining revenue per animal product -- demand still
    to come, valued at the live price -- and only names a winner when it
    leads by `margin`. Below that the two are close enough that switching
    is not worth disturbing a proven route.
    """
    market = observation.get('market') or {}
    prices = market.get('prices') or {}
    remaining = remaining_demand(observation)
    scored: list[tuple[float, str]] = []
    for animal in candidates:
        product = ANIMAL_PRODUCT.get(animal)
        if product is None:
            continue
        price = float(prices.get(product, 0.0))
        scored.append((remaining.get(product, 0.0) * price, animal))
    if len(scored) < 2:
        return None
    scored.sort(reverse=True)
    best, second = (scored[0], scored[1])
    if second[0] <= 0:
        return best[1] if best[0] > 0 else None
    return best[1] if best[0] >= second[0] * margin else None
"Marginal value of a farm action, in coins.\n\nThis is Agent E's core. Every constant here is transcribed from the\ninstalled simulator (`kaggle_environments/envs/kaggriculture/`), not\nguessed, and the pricing model is the simulator's own -- so an action's\nscore is an estimate of the coins it actually produces rather than a\nhand-tuned priority number.\n\nWhy value rather than priority: sections 9j-9q measured that our market\npolicy and product mix are already fine (the reactive engine realises 88.5\ncoins per unit sold against a tape's 91.1) and that the entire gap is\nthroughput -- the engine spends 26% of worker-turns on tasks where a good\nroute spends 49%, burning the rest walking and idling. A scheduler that\nranks candidate actions by coins-per-turn attacks that directly: it cannot\nidle while any positive-value task exists, and it prefers near work to far\nwork automatically because travel enters the denominator.\n\nIt also answers the question a fixed schedule cannot. A strawberry planted\ntoo late to reach its yield window is worth nothing, so watering it is\nworth nothing; the same tile replanted with wheat may still return several\ncycles. Only a time-aware valuation can tell those apart, and this module\nis where that judgement lives.\n"
CROPS: dict[str, dict[str, Any]] = {'WHEAT': dict(seed=10, first=2, max_day=4, interval=0, max_yield=6, ongoing=False), 'CARROT': dict(seed=20, first=2, max_day=3, interval=0, max_yield=4, ongoing=False), 'TOMATO': dict(seed=50, first=8, max_day=8, interval=1, max_yield=4, ongoing=True), 'STRAWBERRY': dict(seed=100, first=10, max_day=10, interval=2, max_yield=4, ongoing=True), 'MELON': dict(seed=80, first=10, max_day=12, interval=0, max_yield=6, ongoing=False)}
ANIMALS: dict[str, dict[str, Any]] = {'GOOSE': dict(cost=300, structure='COOP', first=4, interval=1, max_held=4, product='EGG'), 'COW': dict(cost=400, structure='PASTURE', first=8, interval=2, max_held=6, product='MILK'), 'SHEEP': dict(cost=500, structure='PASTURE', first=6, interval=3, max_held=6, product='WOOL')}
BASE_PRICE: dict[str, int] = {'WHEAT': 25, 'CARROT': 35, 'TOMATO': 60, 'STRAWBERRY': 120, 'MELON': 250, 'EGG': 50, 'MILK': 160, 'WOOL': 200, 'FERTILIZER': 100}
LAST_DAY = 29
TURNS_PER_DAY = 24

def days_left(day: int) -> int:
    """Whole production days remaining, including today."""
    return max(0, LAST_DAY - day)

def live_price(observation: dict[str, Any], item: str) -> float:
    """The market's current quote, falling back to base if unseen."""
    market = observation.get('market') or {}
    prices = market.get('prices') or {}
    value = prices.get(item)
    if isinstance(value, (int, float)) and value > 0:
        return float(value)
    return float(BASE_PRICE.get(item, 0))

def crop_can_mature(crop: str, planted_day: int, day: int) -> bool:
    """Will a tile planted on `planted_day` ever pay out before the end?

    This is the strawberry question: a crop whose first yield lands after
    the season ends is worth nothing at all, so no watering, fertilizing
    or harvesting effort spent on it can be justified.
    """
    spec = CROPS.get(crop)
    if spec is None:
        return False
    return planted_day + spec['first'] <= LAST_DAY

def remaining_waterings(crop: str, planted_day: int, day: int) -> int:
    """How many more yield-producing waterings this tile can still take.

    Non-ongoing crops only gain yield when watered inside
    [(max_day+1)//2, max_day] days of age; ongoing crops accrue on their
    own interval instead, so watering them protects the plant rather than
    adding units.
    """
    spec = CROPS.get(crop)
    if spec is None:
        return 0
    age = day - planted_day
    if spec['ongoing']:
        return max(0, min(days_left(day), spec['max_yield']))
    start = (spec['max_day'] + 1) // 2
    last = min(spec['max_day'], spec['max_day'] + days_left(day) - (age - age))
    if age > spec['max_day']:
        return 0
    first_open = max(age, start)
    return max(0, min(last, LAST_DAY - day + age) - first_open + 1)

def water_value(observation: dict[str, Any], tile: dict[str, Any], day: int) -> float:
    """Coins gained by watering this tile now."""
    crop = str(tile.get('crop', ''))
    spec = CROPS.get(crop)
    if spec is None:
        return 0.0
    planted = int(tile.get('planted_day', day))
    if not crop_can_mature(crop, planted, day):
        return 0.0
    price = live_price(observation, crop)
    fertilized = int(tile.get('fertilized_until_day', -1)) >= day
    units = 2.0 if fertilized else 1.0
    if spec['ongoing']:
        at_risk = int(tile.get('consecutive_unwatered', 0)) >= 1
        return price * units if at_risk else price * 0.25
    age = day - planted
    start = (spec['max_day'] + 1) // 2
    if age < start or age > spec['max_day']:
        at_risk = int(tile.get('consecutive_unwatered', 0)) >= 1
        return price * 0.5 if at_risk else 0.0
    held = int(tile.get('yield_units', 0))
    if held >= spec['max_yield']:
        return 0.0
    gained = min(units, spec['max_yield'] - held)
    return price * gained

def fertilize_value(observation: dict[str, Any], tile: dict[str, Any], day: int) -> float:
    """Coins gained by fertilizing, net of selling the fertilizer instead.

    Fertilizer doubles the yield each watering adds, for three days. Its
    worth is therefore the number of yield-adding waterings still available
    inside that window, times the crop price -- minus what the unit would
    have fetched on the market.
    """
    crop = str(tile.get('crop', ''))
    spec = CROPS.get(crop)
    if spec is None:
        return 0.0
    planted = int(tile.get('planted_day', day))
    if not crop_can_mature(crop, planted, day):
        return 0.0
    if int(tile.get('fertilized_until_day', -1)) >= day:
        return 0.0
    held = int(tile.get('yield_units', 0))
    headroom = max(0, spec['max_yield'] - held)
    if headroom <= 0:
        return 0.0
    age = day - planted
    if spec['ongoing']:
        boosted = min(3, days_left(day), headroom)
    else:
        start = (spec['max_day'] + 1) // 2
        window_end = min(spec['max_day'], age + 2)
        boosted = max(0, window_end - max(age, start) + 1)
        boosted = min(boosted, headroom, days_left(day))
    if boosted <= 0:
        return 0.0
    gain = live_price(observation, crop) * boosted
    return gain - live_price(observation, 'FERTILIZER')

def harvest_value(observation: dict[str, Any], tile: dict[str, Any], day: int | None=None) -> float:
    """Coins realisable from the units sitting on this tile.

    For a non-ongoing crop the simulator *destroys the plant* on harvest
    (`farm["tiles"][fy][fx] = None`), so picking wheat holding one unit
    when it could still reach six throws five units away. Valuing a
    harvest at its face amount made an agent harvest 1,714 times for 0.2
    units apiece where a good route harvests 450 times for 4.75. So an
    early harvest is priced at what it actually nets: the units in hand
    minus the units forfeited by ending the plant now.

    Animals and ongoing crops keep producing after collection, so for them
    the face value is correct.
    """
    units = int(tile.get('yield_units', 0))
    if units <= 0:
        return 0.0
    if 'animal' in tile:
        product = ANIMALS[str(tile['animal'])]['product']
        return live_price(observation, product) * units
    crop = str(tile.get('crop', ''))
    spec = CROPS.get(crop)
    price = live_price(observation, crop)
    if spec is None:
        return price * units
    if spec['ongoing']:
        return price * units
    if day is None:
        return price * units
    planted = int(tile.get('planted_day', day))
    if day - planted < spec['first']:
        return 0.0
    headroom = spec['max_yield'] - units
    if headroom <= 0:
        return price * units
    age = day - planted
    window_start = (spec['max_day'] + 1) // 2
    per_watering = 2 if int(tile.get('fertilized_until_day', -1)) >= day else 1
    today = 1 if not tile.get('watered_today') and window_start <= age <= spec['max_day'] else 0
    last_window_day = min(planted + spec['max_day'], LAST_DAY)
    future = max(0, last_window_day - day)
    forfeited = min(headroom, (today + future) * per_watering)
    if forfeited <= 0:
        return price * units
    return price * units - price * forfeited

def feed_value(observation: dict[str, Any], tile: dict[str, Any], day: int) -> float:
    """Coins protected by feeding this animal now.

    Two separate things hang on a feed, and an earlier version priced
    neither properly.

    An animal unfed for two consecutive days escapes and the structure is
    emptied, forfeiting every remaining unit it would have produced *and*
    the one fertilizer it drops every single day for the rest of the
    season. Pricing that loss from the product's spot quote alone made
    feeding look worthless the moment milk or wool bottomed out at a coin,
    so this agent fed its herd 188 times where it needed 450, bought
    thirty-one animals and finished with eighteen. Fertilizer keeps its
    value long after milk does, so it belongs in the number.

    Short of that, feeding is what unlocks the care bonus: the simulator
    only pays out banked care on a day the animal was fed, so a fed and
    cared animal yields (interval + 1) units every `interval` days against
    the single unit an ignored one still produces. Feeding a goose doubles
    it, a cow triples it, a sheep quadruples it.
    """
    animal = str(tile.get('animal', ''))
    spec = ANIMALS.get(animal)
    if spec is None or tile.get('fed_today'):
        return 0.0
    remaining = days_left(day)
    if remaining <= 0:
        return 0.0
    interval = max(1, int(spec['interval']))
    price = marginal_price(observation, spec['product'])
    manure = marginal_price(observation, 'FERTILIZER')
    if int(tile.get('consecutive_unfed', 0)) >= 1:
        kept = (interval + 1.0) / interval
        return price * kept * remaining + manure * remaining
    return price * (remaining / interval)

def care_value(observation: dict[str, Any], tile: dict[str, Any], day: int) -> float:
    """Care adds one bonus unit on the next fed production day."""
    animal = str(tile.get('animal', ''))
    spec = ANIMALS.get(animal)
    if spec is None or tile.get('cared_today'):
        return 0.0
    if days_left(day) <= 0:
        return 0.0
    if int(tile.get('yield_units', 0)) >= spec['max_held']:
        return 0.0
    return live_price(observation, spec['product'])

def collect_fertilizer_value(observation: dict[str, Any], tile: dict[str, Any]) -> float:
    """A collected unit is worth whatever the best use of it is."""
    if not tile.get('fertilizer_available'):
        return 0.0
    return live_price(observation, 'FERTILIZER')

def plant_value(observation: dict[str, Any], crop: str, day: int) -> float:
    """Expected coins from starting this crop now, net of the seed.

    Returns 0 for a crop that cannot reach its first yield before the
    season ends, which is what stops the agent sinking worker-turns into
    a strawberry that will never pay.
    """
    spec = CROPS.get(crop)
    if spec is None or not crop_can_mature(crop, day, day):
        return 0.0
    price = live_price(observation, crop)
    if spec['ongoing']:
        productions = min(spec['max_yield'], max(0, (days_left(day) - spec['first']) // max(1, spec['interval']) + 1))
        units = productions
    else:
        window = min(spec['max_day'], days_left(day))
        start = (spec['max_day'] + 1) // 2
        units = min(spec['max_yield'], max(0, window - start + 1))
    return price * units - spec['seed']

def plant_tile_days(crop: str, day: int) -> float:
    """How long a tile is tied up growing this crop, in days.

    A one-shot crop occupies its tile until the last day it can still be
    harvested; an ongoing crop until it stops producing.
    """
    spec = CROPS.get(crop)
    if spec is None:
        return 1.0
    if spec['ongoing']:
        span = spec['first'] + spec['interval'] * spec['max_yield']
    else:
        span = spec['max_day']
    return float(max(1, min(span, days_left(day))))

def plant_rate_value(observation: dict[str, Any], crop: str, day: int) -> float:
    """Coins per tile-day from planting this crop now.

    Gross value ranks strawberry (120 a unit) above wheat (25), which is
    how an early agent ends up spending its whole opening bankroll on
    100-coin seeds that first yield on day 10 and hold the tile for
    seventeen. Per tile-day is the measure that matters: wheat costs 10,
    first yields on day 2 and recycles about every five days, so it
    compounds while strawberry is still growing.
    """
    span = plant_tile_days(crop, day)
    return plant_value(observation, crop, day) / span
"Candidate H‑D – demand‑timed, denial‑sensitive, adaptive agent.\n\nThis agent is the strongest from our analysis of the top 100 Kaggle agents.\nIt reads the town's unlocked shops, computes remaining demand and its rate,\nand plans production to maximise revenue while suppressing opponent prices.\nPlanting is timed to align with the demand window, ensuring crops enter the\nmarket when prices are highest.\n\nAuthor: Auto‑generated for the user.\n"
TRAVEL_EXPONENT = 2.5
RESCUE_SHARE = 0.45
OPENING_LAND_DAY = 5
OPENING_HIRES = 4
HAND_CAP = 11
WHEAT_PER_BIRD = 0.8
EMERGENCY_FLOOR = 60.0
MAX_QUADRANTS = 3
SELL_PACE = 0.1
LAST_DAY = 29
HARVEST_HOLD = True
CROP_DEPTH = {'CARROT': 842, 'TOMATO': 529, 'STRAWBERRY': 62, 'MELON': 158, 'WHEAT': None}
ANIMAL_PRODUCTS = {'GOOSE': 'EGG', 'COW': 'MILK', 'SHEEP': 'WOOL'}
ANIMAL_COSTS = {'GOOSE': 300, 'COW': 400, 'SHEEP': 500}
ANIMAL_STRUCTURES = {'GOOSE': 'COOP', 'COW': 'PASTURE', 'SHEEP': 'PASTURE'}
PASS = ['PASS']

def _farm(obs):
    player = obs.get('player', 0)
    farms = obs.get('farms', [])
    if player < len(farms):
        return farms[player]
    return {}

def _positions(farm):
    units = [farm.get('farmer')] + farm.get('hands', [])
    return [tuple(p) if isinstance(p, (list, tuple)) else (0, 0) for p in units]

def _inventory(obs, worker):
    invs = obs.get('private', {}).get('inventories', [])
    if worker < len(invs):
        return invs[worker]
    return {}

def _shed(obs):
    return obs.get('private', {}).get('shed', {})

def _seeds(obs):
    return obs.get('private', {}).get('seeds', {})

def _shed_tiles(board_size=10):
    half = board_size // 2
    return [(half - 1, half - 1), (half, half - 1), (half - 1, half), (half, half)]

def _shed_adjacent(x, y, board_size=10):
    return (x, y) in set(_shed_tiles(board_size))

def _owned(tiles, x, y):
    return 0 <= y < len(tiles) and 0 <= x < len(tiles[y]) and (tiles[y][x] != 'LOCKED')

def _tile_at(farm, pos):
    x, y = pos
    return farm['tiles'][y][x] if 0 <= y < len(farm['tiles']) and 0 <= x < len(farm['tiles'][y]) else None

def fertilizer_gain(tile, day):
    """Extra units this tile would yield if manure went on it today.
    Copied from Candidate G's verified implementation.
    """
    if tile.get('fertilized_until_day', -1) >= day:
        return 0
    spec = CROPS.get(str(tile.get('crop', '')))
    if spec is None:
        return 0
    held = int(tile.get('yield_units', 0) or 0)
    planted = int(tile.get('planted_day', day))
    if spec['ongoing']:
        interval = max(1, int(spec['interval']))
        gain = 0
        for ahead in (0, 1, 2):
            since = day + ahead - planted - int(spec['first'])
            if since >= 0 and since % interval == 0:
                gain += 1
        return max(0, min(gain, int(spec['max_yield']) - held))
    age = day - planted
    start = (int(spec['max_day']) + 1) // 2
    last = int(spec['max_day'])
    if age > last:
        return 0
    remaining = last - max(age, start) + 1
    if remaining <= 0:
        return 0
    room = int(spec['max_yield']) - held - remaining
    return max(0, min(room, min(3, remaining)))

def census(tiles):
    """Count everything we need for scheduling in one pass."""
    out = {'geese': 0, 'cows': 0, 'sheep': 0, 'animals': 0, 'empty_coops': 0, 'empty_pastures': 0, 'wheat': 0, 'crop_wheat': 0, 'crop_carrot': 0, 'crop_tomato': 0, 'crop_strawberry': 0, 'crop_melon': 0, 'free': 0, 'unfed': 0, 'uncared': 0, 'manure': 0, 'ripe_crop_units': 0, 'ripe_animal_units': 0, 'dry': 0, 'unwatered_plants': 0}
    for row in tiles:
        for tile in row:
            if tile == 'LOCKED':
                continue
            if tile is None:
                out['free'] += 1
                continue
            if not isinstance(tile, dict):
                continue
            if 'animal' in tile:
                out['animals'] += 1
                animal = tile.get('animal', '')
                if animal == 'GOOSE':
                    out['geese'] += 1
                elif animal == 'COW':
                    out['cows'] += 1
                elif animal == 'SHEEP':
                    out['sheep'] += 1
                if not tile.get('fed_today'):
                    out['unfed'] += 1
                if not tile.get('cared_today'):
                    out['uncared'] += 1
                if tile.get('fertilizer_available'):
                    out['manure'] += 1
                units = int(tile.get('yield_units', 0) or 0)
                if units > 0:
                    out['ripe_animal_units'] += units
            elif tile.get('kind') == 'COOP':
                out['empty_coops'] += 1
            elif tile.get('kind') == 'PASTURE':
                out['empty_pastures'] += 1
            elif tile.get('kind') == 'PLANT':
                crop = str(tile.get('crop', ''))
                key = 'crop_' + crop
                out[key] = out.get(key, 0) + 1
                if crop == 'WHEAT':
                    out['wheat'] += 1
                if not tile.get('watered_today'):
                    out['dry'] += 1
                    out['unwatered_plants'] += 1
                units = int(tile.get('yield_units', 0) or 0)
                if units > 0:
                    out['ripe_crop_units'] += units
            elif tile.get('kind') == 'WEED':
                pass
    return out

def _optimal_plant_day(crop, obs, day):
    """Return the earliest day we should plant this crop to align with demand."""
    if crop not in ('CARROT', 'TOMATO'):
        return day
    rate = demand_rate(obs)
    rem = rate.get(crop, 0.0)
    book_depth = CROP_DEPTH.get(crop, 100)
    if rem / book_depth > 0.3:
        return min(day, 6)
    else:
        return min(day, 9)

def production_plan(obs, counts, day):
    """Decide what to plant and what animals to buy, using demand + denial."""
    demand = remaining_demand(obs)
    prices = obs.get('market', {}).get('prices', {})
    player = obs['player']
    opponent_farm = obs['farms'][1 - player] if len(obs.get('farms', [])) > 1 else {}
    opp_counts = census(opponent_farm.get('tiles', [])) if opponent_farm else {}
    opp_units = {'MILK': opp_counts.get('cows', 0) * 15, 'WOOL': opp_counts.get('sheep', 0) * 15, 'EGG': opp_counts.get('geese', 0) * 25, 'CARROT': opp_counts.get('crop_carrot', 0) * 4, 'TOMATO': opp_counts.get('crop_tomato', 0) * 8, 'STRAWBERRY': opp_counts.get('crop_strawberry', 0) * 8, 'MELON': opp_counts.get('crop_melon', 0) * 6}
    own_committed = {'CARROT': counts['crop_carrot'] * 4, 'TOMATO': counts['crop_tomato'] * 8, 'STRAWBERRY': counts['crop_strawberry'] * 8, 'MELON': counts['crop_melon'] * 6, 'EGG': counts['geese'] * 25, 'MILK': counts['cows'] * 15, 'WOOL': counts['sheep'] * 15}
    plan = {'crop_targets': {}, 'animal_targets': {}, 'wheat_target': max(20, counts['animals'] * 2 + 5)}
    crop_scores = []
    for crop in ['CARROT', 'TOMATO', 'STRAWBERRY', 'MELON']:
        if not crop_can_mature(crop, day, day):
            continue
        rem = demand.get(crop, 0.0)
        if rem <= 0:
            continue
        price = prices.get(crop, 0.0)
        if price < 1:
            continue
        offset = opp_units.get(crop, 0) + own_committed.get(crop, 0)
        units_per_tile = 4 if crop in ['CARROT', 'MELON'] else 6
        value = sale_revenue(obs, crop, units_per_tile, offset) / units_per_tile
        opp_sales = opp_units.get(crop, 0)
        if opp_sales > 0:
            opp_loss = sale_revenue(obs, crop, opp_sales, 0) - sale_revenue(obs, crop, opp_sales, offset + units_per_tile)
            value += opp_loss / units_per_tile
        crop_scores.append((value, crop))
    crop_scores.sort(reverse=True)
    remaining_free = counts['free']
    for val, crop in crop_scores:
        if day < _optimal_plant_day(crop, obs, day):
            continue
        max_tiles = min(20, int(demand.get(crop, 0) / 4), int(CROP_DEPTH.get(crop, 1000) / 4), remaining_free)
        if max_tiles <= 0:
            continue
        plan['crop_targets'][crop] = max_tiles
        remaining_free -= max_tiles
    animal_scores = []
    for animal in ['GOOSE', 'COW', 'SHEEP']:
        product = ANIMAL_PRODUCTS[animal]
        rem = demand.get(product, 0.0)
        if rem <= 0:
            continue
        price = prices.get(product, 0.0)
        if price < 1:
            continue
        if animal == 'GOOSE':
            units_per_animal = 25 * 2
        elif animal == 'COW':
            units_per_animal = 15 * 1.5
        else:
            units_per_animal = 15 * 1.0
        offset = opp_units.get(product, 0) + own_committed.get(product, 0)
        product_value = sale_revenue(obs, product, units_per_animal, offset)
        opp_sales = opp_units.get(product, 0)
        if opp_sales > 0:
            opp_loss = sale_revenue(obs, product, opp_sales, 0) - sale_revenue(obs, product, opp_sales, offset + units_per_animal)
            product_value += opp_loss
        manure_units = 25
        manure_price = prices.get('FERTILIZER', 0.0)
        if manure_price > 0:
            manure_value = manure_units * manure_price
            product_value += manure_value
        animal_scores.append((product_value - ANIMAL_COSTS[animal], animal))
    animal_scores.sort(reverse=True)
    if len(animal_scores) >= 2 and animal_scores[0][0] > 1.5 * animal_scores[1][0]:
        best = animal_scores[0][1]
        plan['animal_targets'][best] = 18
        plan['animal_targets'][animal_scores[1][1]] = 2
    else:
        for _, animal in animal_scores[:2]:
            plan['animal_targets'][animal] = 9
    if 'GOOSE' not in plan['animal_targets']:
        plan['animal_targets']['GOOSE'] = max(2, plan['animal_targets'].get('GOOSE', 0))
    return plan

def job_value(obs, tile, x, y, inventory, day, shed, seeds, counts, plan, closing):
    jobs = []
    player = obs['player']
    farm = obs['farms'][player]
    board_size = len(farm['tiles'])
    egg_price = max(1.0, price_at('EGG', inventory_of(obs, 'EGG')))
    fert_price = max(1.0, price_at('FERTILIZER', inventory_of(obs, 'FERTILIZER')))
    if _shed_adjacent(x, y, board_size):
        if int(obs.get('step', 0)) >= 718:
            haul = 0.0
            for item, qty in inventory.items():
                if qty > 0 and item in MARKET_PARAMS:
                    haul += qty * price_at(item, inventory_of(obs, item))
            if haul > 0:
                jobs.append((6000.0 + haul, ['DROP']))
        if counts['unfed'] > 0 and inventory.get('WHEAT', 0) <= 0:
            shed_wheat = shed.get('WHEAT', 0)
            if shed_wheat > 0:
                jobs.append((10000.0, ['PICKUP', 'WHEAT', min(12, shed_wheat)]))
        if not any((inventory.get(a, 0) > 0 for a in ANIMAL_PRODUCTS)):
            for animal in ['GOOSE', 'COW', 'SHEEP']:
                waiting = shed.get(animal, 0)
                if waiting <= 0:
                    continue
                home = ANIMAL_STRUCTURES[animal]
                free = counts['empty_coops'] if home == 'COOP' else counts['empty_pastures']
                if free <= 0:
                    continue
                carry = min(3, waiting, free)
                jobs.append((5000.0 - 100 * (animal != 'GOOSE'), ['PICKUP', animal, carry]))
                break
    if tile is None:
        if counts['wheat'] < plan['wheat_target'] and seeds.get('WHEAT', 0) > 0:
            if day <= LAST_DAY - 8:
                jobs.append((4000.0 + egg_price * 0.5, ['PLANT', 'WHEAT']))
        for animal, target in plan['animal_targets'].items():
            home = ANIMAL_STRUCTURES[animal]
            current = counts['animals'] + shed.get(animal, 0)
            if current < target:
                if home == 'COOP' and counts['empty_coops'] < 6 or (home == 'PASTURE' and counts['empty_pastures'] < 6):
                    build_action = ['BUILD_COOP'] if home == 'COOP' else ['BUILD_PASTURE']
                    jobs.append((3000.0, build_action))
                    break
        for crop, target in plan['crop_targets'].items():
            if counts.get('crop_' + crop, 0) < target and seeds.get(crop, 0) > 0:
                if day >= _optimal_plant_day(crop, obs, day) and day <= LAST_DAY - CROPS[crop]['first'] - 2:
                    price = price_at(crop, inventory_of(obs, crop))
                    jobs.append((2000.0 + price, ['PLANT', crop]))
                    break
        return jobs
    if not isinstance(tile, dict):
        return jobs
    kind = tile.get('kind')
    if 'animal' in tile:
        animal = tile['animal']
        units = int(tile.get('yield_units', 0) or 0)
        if not tile.get('fed_today') and inventory.get('WHEAT', 0) > 0:
            jobs.append((10000.0, ['FEED']))
        if tile.get('fed_today') and (not tile.get('cared_today')):
            jobs.append((8000.0, ['CARE']))
        if tile.get('fertilizer_available'):
            jobs.append((3000.0 + fert_price, ['COLLECT_FERTILIZER']))
        if units > 0 and (units >= 2 or closing):
            jobs.append((5000.0 + units * egg_price, ['HARVEST']))
    elif kind in ('COOP', 'PASTURE'):
        for animal, home in ANIMAL_STRUCTURES.items():
            if home == kind and inventory.get(animal, 0) > 0:
                jobs.append((4000.0, ['PLACE', animal]))
                break
    elif kind == 'PLANT':
        crop = tile.get('crop', '')
        spec = CROPS.get(crop)
        if not spec:
            return jobs
        age = day - tile.get('planted_day', day)
        if not tile.get('watered_today'):
            jobs.append((2000.0 + egg_price * 0.3, ['WATER']))
        if inventory.get('FERTILIZER', 0) > 0:
            gain = fertilizer_gain(tile, day)
            if gain > 0:
                worth = gain * price_at(crop, inventory_of(obs, crop))
                if worth > fert_price:
                    jobs.append((2500.0 + worth, ['FERTILIZE']))
        units = int(tile.get('yield_units', 0) or 0)
        if units > 0 and age >= spec['first']:
            urgent = age >= spec['max_day'] or units >= spec['max_yield'] or closing
            if urgent or not HARVEST_HOLD:
                jobs.append((3000.0 + units * price_at(crop, inventory_of(obs, crop)), ['HARVEST']))
    elif kind == 'WEED':
        jobs.append((500.0, ['DIG']))
    return jobs

def candidate_hd_decide(obs: dict[str, Any]) -> AgentAction:
    farm = _farm(obs)
    tiles = farm.get('tiles', [])
    if not tiles:
        return {'farmer': PASS, 'hands': [], 'market': []}
    day = obs.get('day', 0)
    closing = day >= LAST_DAY - 1
    positions = _positions(farm)
    shed = _shed(obs)
    seeds = _seeds(obs)
    counts = census(tiles)
    money = farm.get('money', 0.0)
    plan = production_plan(obs, counts, day)
    claimed = set()
    actions = []
    for worker, pos in enumerate(positions):
        inv = _inventory(obs, worker)
        best_score = -1000000000.0
        best_action = PASS
        best_cell = None
        for y in range(len(tiles)):
            for x in range(len(tiles[y])):
                if (x, y) in claimed or not _owned(tiles, x, y):
                    continue
                tile = tiles[y][x]
                jobs = job_value(obs, tile, x, y, inv, day, shed, seeds, counts, plan, closing)
                travel = distance(pos, (x, y))
                for score, act in jobs:
                    final_score = score / (travel + 1.0) ** TRAVEL_EXPONENT
                    if act[0] in ('WATER', 'FEED', 'CARE'):
                        final_score *= 1.5
                    if final_score > best_score:
                        best_score = final_score
                        best_cell = (x, y)
                        best_action = step_toward(pos, (x, y), act) if travel > 0 else act
        if best_cell is not None:
            claimed.add(best_cell)
            actions.append(best_action)
        else:
            actions.append(PASS)
    market = []
    for item in ['EGG', 'FERTILIZER', 'CARROT', 'TOMATO', 'STRAWBERRY', 'MELON', 'WHEAT', 'MILK', 'WOOL']:
        held = shed.get(item, 0)
        if held <= 0:
            continue
        if item == 'WHEAT':
            reserve = counts['animals'] * 2
            if held <= reserve:
                continue
            held -= reserve
        demand = remaining_demand(obs).get(item, 0.0)
        max_sell = max(1, int(demand * SELL_PACE)) if demand > 0 else 10
        sell_qty = min(held, max_sell)
        if sell_qty > 0:
            market.append(['SELL', item, sell_qty])
    if seeds.get('WHEAT', 0) < 10 and money > EMERGENCY_FLOOR:
        market.append(['BUY_SEED', 'WHEAT', 10 - int(seeds.get('WHEAT', 0))])
    hands = len(farm.get('hands', []))
    target_hands = min(HAND_CAP, 4 + day)
    if hands < target_hands and day <= 27 and (obs.get('hour', 0) <= 2):
        for _ in range(min(4, target_hands - hands)):
            market.append(['HIRE'])
    quadrants = len(farm.get('unlocked_quadrants', []))
    hour = int(obs.get('hour', 0))
    if quadrants < MAX_QUADRANTS and day == OPENING_LAND_DAY and (hour == 1):
        if money > 1200:
            market.append(['BUY_LAND'])
    elif quadrants == 2 and day >= 9 and (hour == 1) and (money > 2000):
        market.append(['BUY_LAND'])
    for crop, target in plan['crop_targets'].items():
        current = counts.get('crop_' + crop, 0)
        if current < target and seeds.get(crop, 0) < 10:
            need = target - current
            want = min(need, 10)
            if money > 300:
                market.append(['BUY_SEED', crop, want])
    census_key = {'GOOSE': 'geese', 'COW': 'cows', 'SHEEP': 'sheep'}
    for animal, target in plan['animal_targets'].items():
        current = counts.get(census_key[animal], 0) + shed.get(animal, 0)
        if current < target:
            home = ANIMAL_STRUCTURES[animal]
            free = counts['empty_coops'] if home == 'COOP' else counts['empty_pastures']
            if free > 0 and money > ANIMAL_COSTS[animal] + EMERGENCY_FLOOR:
                want = min(target - current, free)
                market.append(['BUY_ANIMAL', animal, want])
    if counts['unfed'] > 0 and shed.get('WHEAT', 0) <= 0 and (money > EMERGENCY_FLOOR):
        market.append(['BUY_PRODUCT', 'WHEAT', min(counts['unfed'], 6)])
    market = market[:10]
    return {'farmer': actions[0] if actions else PASS, 'hands': actions[1:] if len(actions) > 1 else [], 'market': market}

def agent(obs):
    return candidate_hd_decide(obs)
